[package]
name = "voxelith-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
flate2 = "1.0"
voxelith = { path = "..", default-features = false }

[[bin]]
name = "vox"
path = "fuzz_targets/vox.rs"
test = false
doc = false
bench = false

[[bin]]
name = "glb"
path = "fuzz_targets/glb.rs"
test = false
doc = false
bench = false

[[bin]]
name = "vxlt"
path = "fuzz_targets/vxlt.rs"
test = false
doc = false
bench = false
